In [2]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /opt/anaconda3/envs/a3/lib/python3.8/site-packages (1.3.4)
Requirement already satisfied: pytz>=2017.3 in /opt/anaconda3/envs/a3/lib/python3.8/site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.17.3; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10" in /opt/anaconda3/envs/a3/lib/python3.8/site-packages (from pandas) (1.19.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/anaconda3/envs/a3/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/a3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [70]:
import numpy as np
import datetime

In [214]:
path = '../data_preparation/model/classifiedNBAData.csv'
df = pd.read_csv(path, index_col=0).dropna()
df = df[df.Team != "warriors"] # dropping because of data issues
df = df[df.Team != "clippers"] # dropping because of data issues

In [215]:
df['Date'] = pd.to_datetime(df['Date'])
df['Date'] = df['Date'].map(lambda x: x.date())

In [216]:
df

,Team,Date,Tweet,RF Positive,RF Negative,NB Positive,NB Negative,LR Positive,LR Negative
0,celtics,2021-11-09,RT @Ballislife: 33 YEARS AGO TODAY üêê\nMichael ...,0.539399,0.460601,0.634729,0.365271,0.614852,0.385148
1,celtics,2021-11-09,Coming up at 6 w/ @MutWEEI \n\n‚ñ∂Ô∏è OBJ Watch is...,0.367433,0.632567,0.298787,0.701213,0.233022,0.766978
2,celtics,2021-11-09,"RT @TDISportsClips: November 9, 2013: Jeff Gre...",0.546077,0.453923,0.591005,0.408995,0.563533,0.436467
3,celtics,2021-11-09,Who the f is Thomas lol https://t.co/uWolEgzSQk,0.637100,0.362900,0.638071,0.361929,0.887898,0.112102
4,celtics,2021-11-09,RT @Ballislife: 33 YEARS AGO TODAY üêê\nMichael ...,0.539399,0.460601,0.634729,0.365271,0.614852,0.385148
...,...,...,...,...,...,...,...,...,...
53508,spurs,2021-11-28,@SaxyKeN17 @SpursOfficial Now I feel guilty be...,0.525547,0.474453,0.724370,0.275630,0.776781,0.223219
53509,spurs,2021-11-28,"@FPL__Raptor Nigga you have triple spurs, go w...",0.638787,0.361213,0.518403,0.481597,0.703827,0.296173
53510,spurs,2021-11-28,"@rogersanders Yep, don‚Äôt blame you. I‚Äôve been ...",0.543863,0.456137,0.602742,0.397258,0.725468,0.274532
53511,spurs,2021-11-28,@paddypower Wouldn‚Äôt be surpised. He manages S...,0.546077,0.453923,0.499836,0.500164,0.610939,0.389061
53512,spurs,2021-11-28,John Moss decided it wasn‚Äôt a pen for us again...,0.510555,0.489445,0.440538,0.559462,0.403308,0.596692

In [217]:
line_data = df.groupby(['Team', 'Date'])['RF Positive', 'RF Negative', 'NB Positive', 'NB Negative', 'LR Positive', 'LR Negative'].mean()

<ipython-input-217-538e282e9a9e>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  line_data = df.groupby(['Team', 'Date'])['RF Positive', 'RF Negative', 'NB Positive', 'NB Negative', 'LR Positive', 'LR Negative'].mean()

In [218]:
pd.set_option("display.max_rows", 20)
line_data

                    RF Positive  RF Negative  NB Positive  NB Negative  \
Team    Date
76ers   2021-11-09     0.542106     0.457894     0.572901     0.427099
        2021-11-11     0.516066     0.483934     0.534252     0.465748
        2021-11-12     0.519677     0.480323     0.597096     0.402904
        2021-11-13     0.522594     0.477406     0.544097     0.455903
        2021-11-14     0.517971     0.482029     0.559209     0.440791
...                         ...          ...          ...          ...
wizards 2021-11-25     0.542437     0.457563     0.588558     0.411442
        2021-11-26     0.563477     0.436523     0.632225     0.367775
        2021-11-27     0.561644     0.438356     0.619156     0.380844
        2021-11-28     0.543694     0.456306     0.626345     0.373655
        2021-11-29     0.538272     0.461728     0.611926     0.388074

                    LR Positive  LR Negative
Team    Date
76ers   2021-11-09     0.589559     0.410441
        2021-11-11     0.532571     0.467429
        2021-11-12     0.618621     0.381379
        2021-11-13     0.568283     0.431717
        2021-11-14     0.556959     0.443041
...                         ...          ...
wizards 2021-11-25     0.622626     0.377374
        2021-11-26     0.680348     0.319652
        2021-11-27     0.675928     0.324072
        2021-11-28     0.656721     0.343279
        2021-11-29     0.638956     0.361044

[476 rows x 6 columns]

In [219]:
counts = df
counts['RF Positive'] = np.where((df['RF Positive'] >= .5), 1, df['RF Positive'])
counts['RF Positive'] = np.where((df['RF Positive'] < .5), 0, df['RF Positive'])

counts['RF Negative'] = np.where((df['RF Negative'] >= .5), 1, df['RF Negative'])
counts['RF Negative'] = np.where((df['RF Negative'] < .5), 0, df['RF Negative'])

counts['NB Positive'] = np.where((df['NB Positive'] >= .5), 1, df['NB Positive'])
counts['NB Positive'] = np.where((df['NB Positive'] < .5), 0, df['NB Positive'])

counts['NB Negative'] = np.where((df['NB Negative'] >= .5), 1, df['NB Negative'])
counts['NB Negative'] = np.where((df['NB Negative'] < .5), 0, df['NB Negative'])

counts['LR Positive'] = np.where((df['LR Positive'] >= .5), 1, df['LR Positive'])
counts['LR Positive'] = np.where((df['LR Positive'] < .5), 0, df['LR Positive'])

counts['LR Negative'] = np.where((df['LR Negative'] >= .5), 1, df['LR Negative'])
counts['LR Negative'] = np.where((df['LR Negative'] < .5), 0, df['LR Negative'])

counts

for_tweets = counts.copy()

In [220]:
counts = df.groupby(['Team', 'Date'])['RF Positive', 'RF Negative', 'NB Positive', 'NB Negative', 'LR Positive', 'LR Negative'].sum()

<ipython-input-220-cf7ba7606989>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  counts = df.groupby(['Team', 'Date'])['RF Positive', 'RF Negative', 'NB Positive', 'NB Negative', 'LR Positive', 'LR Negative'].sum()

In [221]:
counts = counts.astype({'RF Positive': 'int32', 'RF Negative': 'int32', 'NB Positive': 'int32', 'NB Negative': 'int32', 'LR Positive': 'int32', 'LR Negative': 'int32'})
counts

                    RF Positive  RF Negative  NB Positive  NB Negative  \
Team    Date
76ers   2021-11-09          110           10           96           24
        2021-11-11           81           19           65           35
        2021-11-12          158           42          166           34
        2021-11-13           83           17           64           36
        2021-11-14           75           25           76           24
...                         ...          ...          ...          ...
wizards 2021-11-25           93            7           80           20
        2021-11-26           90           10           75           25
        2021-11-27           92            8           82           18
        2021-11-28           82           17           75           24
        2021-11-29           85           15           82           18

                    LR Positive  LR Negative
Team    Date
76ers   2021-11-09           95           25
        2021-11-11           57           43
        2021-11-12          160           40
        2021-11-13           70           30
        2021-11-14           74           26
...                         ...          ...
wizards 2021-11-25           87           13
        2021-11-26           81           19
        2021-11-27           88           12
        2021-11-28           74           25
        2021-11-29           85           15

[476 rows x 6 columns]

In [222]:
print("Range of num tweets: ", counts['RF Positive'].min(),"-", counts['RF Positive'].max())

Range of num tweets:  46 - 197

In [223]:
counts.to_csv('tweet_counts.csv')

In [224]:
for_tweets

,Team,Date,Tweet,RF Positive,RF Negative,NB Positive,NB Negative,LR Positive,LR Negative
0,celtics,2021-11-09,RT @Ballislife: 33 YEARS AGO TODAY üêê\nMichael ...,1.0,0.0,1.0,0.0,1.0,0.0
1,celtics,2021-11-09,Coming up at 6 w/ @MutWEEI \n\n‚ñ∂Ô∏è OBJ Watch is...,0.0,1.0,0.0,1.0,0.0,1.0
2,celtics,2021-11-09,"RT @TDISportsClips: November 9, 2013: Jeff Gre...",1.0,0.0,1.0,0.0,1.0,0.0
3,celtics,2021-11-09,Who the f is Thomas lol https://t.co/uWolEgzSQk,1.0,0.0,1.0,0.0,1.0,0.0
4,celtics,2021-11-09,RT @Ballislife: 33 YEARS AGO TODAY üêê\nMichael ...,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
53508,spurs,2021-11-28,@SaxyKeN17 @SpursOfficial Now I feel guilty be...,1.0,0.0,1.0,0.0,1.0,0.0
53509,spurs,2021-11-28,"@FPL__Raptor Nigga you have triple spurs, go w...",1.0,0.0,1.0,0.0,1.0,0.0
53510,spurs,2021-11-28,"@rogersanders Yep, don‚Äôt blame you. I‚Äôve been ...",1.0,0.0,1.0,0.0,1.0,0.0
53511,spurs,2021-11-28,@paddypower Wouldn‚Äôt be surpised. He manages S...,1.0,0.0,0.0,1.0,1.0,0.0
53512,spurs,2021-11-28,John Moss decided it wasn‚Äôt a pen for us again...,1.0,0.0,0.0,1.0,0.0,1.0

In [225]:
# subsample 1 positive and 1 negative tweet per team per day
cols = ['Team', 'Date', 'Tweet', 'Sentiment', 'Model']
tweets = pd.DataFrame(columns = cols)
positive_tweets = for_tweets.sort_values('RF Positive').groupby(['Team', 'Date']).last()
negative_tweets = for_tweets.sort_values('RF Negative').groupby(['Team', 'Date']).last()
negative_tweets

                                                                Tweet  \
Team    Date
76ers   2021-11-09     Fuck the 76ers and the beat . Soft fraud teams
        2021-11-11  So I guess all were gonna get on NBA tv is War...
        2021-11-12  @CombatChr I don't think Rich screwed up. I th...
        2021-11-13  RT @JoeyBurton: Whether it‚Äôs on the road or at...
        2021-11-14  RT @HukAleksandra: It's unreal how @cryptocom ...
...                                                               ...
wizards 2021-11-25                @Spheza18 @Wizards_DnDDE  need help
        2021-11-26  If the wizards lose today. Y‚Äôall can go head a...
        2021-11-27  Wizards try to put Giddey in pick and roll vs....
        2021-11-28  RT @xavierck3d: wizards only want one thing an...
        2021-11-29  RT @xavierck3d: wizards only want one thing an...

                    RF Positive  RF Negative  NB Positive  NB Negative  \
Team    Date
76ers   2021-11-09          0.0          1.0          1.0          0.0
        2021-11-11          0.0          1.0          0.0          1.0
        2021-11-12          0.0          1.0          0.0          1.0
        2021-11-13          0.0          1.0          1.0          0.0
        2021-11-14          0.0          1.0          1.0          0.0
...                         ...          ...          ...          ...
wizards 2021-11-25          0.0          1.0          0.0          1.0
        2021-11-26          0.0          1.0          0.0          1.0
        2021-11-27          0.0          1.0          0.0          1.0
        2021-11-28          0.0          1.0          1.0          0.0
        2021-11-29          0.0          1.0          1.0          0.0

                    LR Positive  LR Negative
Team    Date
76ers   2021-11-09          1.0          0.0
        2021-11-11          0.0          1.0
        2021-11-12          0.0          1.0
        2021-11-13          1.0          0.0
        2021-11-14          1.0          0.0
...                         ...          ...
wizards 2021-11-25          0.0          1.0
        2021-11-26          0.0          1.0
        2021-11-27          1.0          0.0
        2021-11-28          0.0          1.0
        2021-11-29          0.0          1.0

[476 rows x 7 columns]

In [226]:
# positive_tweets.printSchema
rf_positive_tweets = positive_tweets['Tweet'].copy()
rf_positive_tweets.to_csv('rf_positive_tweets.csv')

In [227]:
rf_negative_tweets = negative_tweets['Tweet'].copy()
rf_negative_tweets.to_csv('rf_negative_tweets.csv')

In [228]:
print(sorted(df['Team'].unique()))

['76ers', 'blazers', 'bucks', 'bulls', 'cavaliers', 'celtics', 'grizzlies', 'hawks', 'heat', 'hornets', 'jazz', 'kings', 'knicks', 'lakers', 'magic', 'mavericks', 'nets', 'nuggets', 'pacers', 'pelicans', 'pistons', 'raptors', 'rockets', 'spurs', 'suns', 'thunder', 'timberwolves', 'wizards']

In [229]:
# subsample 1 positive and 1 negative tweet per team per day
cols = ['Team', 'Date', 'Tweet', 'Sentiment', 'Model']
tweets = pd.DataFrame(columns = cols)
positive_tweets = for_tweets.sort_values('NB Positive').groupby(['Team', 'Date']).last()
negative_tweets = for_tweets.sort_values('NB Negative').groupby(['Team', 'Date']).last()
negative_tweets

                                                                Tweet  \
Team    Date
76ers   2021-11-09  NBA 3 LOCK PLAY üîíüîíüîí \n76ers vs Bucks üèÄ\nOur to...
        2021-11-11  NEW YORK (AFP) ‚Äî Giannis Antetokounmpo got bac...
        2021-11-12  „Åì„ÅÜ„ÅÑ„ÅÜ‰ª£ÁêÜ‰∫∫„Åå„Åä„Åã„Åó„Åè„Åó„Åü„Çì„Å†„Å®ÊÄù„Å£„Å¶„Çã„ÄÇ„Åù„Çä„ÇÉÁ´ãÂ†¥Èå†Ê®©Âà©Ê®©Âà©Ë®Ä„ÅÜ„Çà„Å≠„ÄÇ„Åù„Çå„Åå‰ªï‰∫ã„Å†„ÇÇ„Çì„ÄÇ...
        2021-11-13  #NBA75\nNovember Thirteenth =95\nPHILADELPHIA ...
        2021-11-14  The Philadelphia 76ers discuss just how much t...
...                                                               ...
wizards 2021-11-25  @Wizards_MagicBR @Kidzastr Akahxjwbduebdhej ad...
        2021-11-26  What time you get off I‚Äôll slide on you I been...
        2021-11-27  „Çà„Åè‰ºë„Çì„Åß„ÅÑ„Çã„Éû„Éº„Éô„É™„ÉÉ„ÇØ„Çπ„Å´ÂèçÂØæ„Åô„Çã„Çà„ÅÜ„Å´Ë®≠ÂÆö„Åï„Çå„Åü„Ç¶„Ç£„Ç∂„Éº„Éâhttps://t.co/C...
        2021-11-28  @MWharam7 I agree I think all the names that w...
        2021-11-29  @SociosHoops @socios Magic\nThunder\nBulls\nHe...

                    RF Positive  RF Negative  NB Positive  NB Negative  \
Team    Date
76ers   2021-11-09          0.0          1.0          0.0          1.0
        2021-11-11          1.0          0.0          0.0          1.0
        2021-11-12          1.0          0.0          0.0          1.0
        2021-11-13          1.0          0.0          0.0          1.0
        2021-11-14          0.0          1.0          0.0          1.0
...                         ...          ...          ...          ...
wizards 2021-11-25          1.0          0.0          0.0          1.0
        2021-11-26          0.0          1.0          0.0          1.0
        2021-11-27          1.0          0.0          0.0          1.0
        2021-11-28          0.0          1.0          0.0          1.0
        2021-11-29          1.0          0.0          0.0          1.0

                    LR Positive  LR Negative
Team    Date
76ers   2021-11-09          0.0          1.0
        2021-11-11          0.0          1.0
        2021-11-12          1.0          0.0
        2021-11-13          1.0          0.0
        2021-11-14          0.0          1.0
...                         ...          ...
wizards 2021-11-25          1.0          0.0
        2021-11-26          0.0          1.0
        2021-11-27          1.0          0.0
        2021-11-28          0.0          1.0
        2021-11-29          0.0          1.0

[476 rows x 7 columns]

In [230]:
nb_positive_tweets = positive_tweets['Tweet'].copy()
nb_positive_tweets.to_csv('nb_positive_tweets.csv')
nb_negative_tweets = negative_tweets['Tweet'].copy()
nb_negative_tweets.to_csv('nb_negative_tweets.csv')

In [231]:
# subsample 1 positive and 1 negative tweet per team per day
cols = ['Team', 'Date', 'Tweet', 'Sentiment', 'Model']
tweets = pd.DataFrame(columns = cols)
positive_tweets = for_tweets.sort_values('LR Positive').groupby(['Team', 'Date']).last()
negative_tweets = for_tweets.sort_values('LR Negative').groupby(['Team', 'Date']).last()
negative_tweets

                                                                Tweet  \
Team    Date
76ers   2021-11-09  76ers vs. Bucks live stream info, TV channel: ...
        2021-11-11  RT @YoungNBA: Top 10 halfcourt offenses after ...
        2021-11-12  Do they keep you in a cell? Cells.\nWhen you'r...
        2021-11-13  @CaipiraTips Miami\n76ers\nWizards\nPelicans\n...
        2021-11-14  üî¥ IN LIVE\n\nWells Fargo Center, Philadelphia,...
...                                                               ...
wizards 2021-11-25  RT @mr_scientism: The US elite are like wizard...
        2021-11-26  So far we're 2/5. I need us to beat Wizards an...
        2021-11-27  The #Wizards need a win tonight against the #M...
        2021-11-28  @OttoSuwenNFT @Treasure_NFT @SmolBrainsNFT Wha...
        2021-11-29  NGL I like what I see with Unfinity but I'm a ...

                    RF Positive  RF Negative  NB Positive  NB Negative  \
Team    Date
76ers   2021-11-09          1.0          0.0          1.0          0.0
        2021-11-11          1.0          0.0          1.0          0.0
        2021-11-12          0.0          1.0          0.0          1.0
        2021-11-13          1.0          0.0          0.0          1.0
        2021-11-14          1.0          0.0          0.0          1.0
...                         ...          ...          ...          ...
wizards 2021-11-25          0.0          1.0          0.0          1.0
        2021-11-26          0.0          1.0          0.0          1.0
        2021-11-27          0.0          1.0          1.0          0.0
        2021-11-28          1.0          0.0          0.0          1.0
        2021-11-29          1.0          0.0          0.0          1.0

                    LR Positive  LR Negative
Team    Date
76ers   2021-11-09          0.0          1.0
        2021-11-11          0.0          1.0
        2021-11-12          0.0          1.0
        2021-11-13          0.0          1.0
        2021-11-14          0.0          1.0
...                         ...          ...
wizards 2021-11-25          0.0          1.0
        2021-11-26          0.0          1.0
        2021-11-27          0.0          1.0
        2021-11-28          0.0          1.0
        2021-11-29          0.0          1.0

[476 rows x 7 columns]

In [232]:
lr_positive_tweets = positive_tweets['Tweet'].copy()
lr_positive_tweets.to_csv('lr_positive_tweets.csv')
lr_negative_tweets = negative_tweets['Tweet'].copy()
lr_negative_tweets.to_csv('lr_negative_tweets.csv')

In [233]:
for_tweets

,Team,Date,Tweet,RF Positive,RF Negative,NB Positive,NB Negative,LR Positive,LR Negative
0,celtics,2021-11-09,RT @Ballislife: 33 YEARS AGO TODAY üêê\nMichael ...,1.0,0.0,1.0,0.0,1.0,0.0
1,celtics,2021-11-09,Coming up at 6 w/ @MutWEEI \n\n‚ñ∂Ô∏è OBJ Watch is...,0.0,1.0,0.0,1.0,0.0,1.0
2,celtics,2021-11-09,"RT @TDISportsClips: November 9, 2013: Jeff Gre...",1.0,0.0,1.0,0.0,1.0,0.0
3,celtics,2021-11-09,Who the f is Thomas lol https://t.co/uWolEgzSQk,1.0,0.0,1.0,0.0,1.0,0.0
4,celtics,2021-11-09,RT @Ballislife: 33 YEARS AGO TODAY üêê\nMichael ...,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
53508,spurs,2021-11-28,@SaxyKeN17 @SpursOfficial Now I feel guilty be...,1.0,0.0,1.0,0.0,1.0,0.0
53509,spurs,2021-11-28,"@FPL__Raptor Nigga you have triple spurs, go w...",1.0,0.0,1.0,0.0,1.0,0.0
53510,spurs,2021-11-28,"@rogersanders Yep, don‚Äôt blame you. I‚Äôve been ...",1.0,0.0,1.0,0.0,1.0,0.0
53511,spurs,2021-11-28,@paddypower Wouldn‚Äôt be surpised. He manages S...,1.0,0.0,0.0,1.0,1.0,0.0
53512,spurs,2021-11-28,John Moss decided it wasn‚Äôt a pen for us again...,1.0,0.0,0.0,1.0,0.0,1.0

In [234]:
new_rf_positive_tweets = pd.read_csv("rf_positive_tweets.csv", index_col=0)
new_rf_positive_tweets['Date'] = new_rf_positive_tweets['Date'].astype(str)
print(new_rf_positive_tweets.loc[(new_rf_positive_tweets['Date'] == '2021-11-18')])
# wizards['Date'] = wizards['Date'].astype(str)
# wizards = wizards.loc[(for_tweets['Team'] == 'wizards')  & (wizards['Date'] == '2021-11-18')]

Empty DataFrame
Columns: [Date, Tweet]
Index: []

In [235]:
new_rf_positive_tweets

               Date                                              Tweet
Team
76ers    2021-11-09  RT @FranFermoso: Se me acab√≥ lo de vivir del c...
76ers    2021-11-11  @Smaug55 I don't think 76ers will get a better...
76ers    2021-11-12  RT @TheyCallMeJL_94: @DerekBodnerNBA Funny Ric...
76ers    2021-11-13  Philadelphia 76ers vs Indiana Pacers 11/13/202...
76ers    2021-11-14  RT @BitSler: üèÄ#NBA in 15 min üèÄ\n\nBET NOW ‚û°Ô∏èht...
...             ...                                                ...
wizards  2021-11-25  @grr_mono was verr√ºcktes, mittelaltes?\n\nWiza...
wizards  2021-11-26  @labandamonored @wizards_magicES Osea acord√°is...
wizards  2021-11-27  RT @mahoyaku_eng: [2nd Anniversary Limited Loc...
wizards  2021-11-28  Your Daily Deals! üì≤\n\nhttps://t.co/xLnvmJZybx...
wizards  2021-11-29  RT @DimirUB: „ÄêUnfinity„Äë\nÂÆáÂÆôÂü∫Êú¨ÂúüÂú∞\nhttps://t.co/...

[476 rows x 2 columns]